---
# Site details
site_name: 'AWesome SHell'
site_description: Load and use your AWS identities with all your favorite AWS tools
site_author: Hestio


# Source code repo
repo_url: 'https://github.com/hest-io/awsh'


# Style and Theme
theme:
  name: material
  palette:
    accent: 'blue'
  social:
    - type: 'github'
      link: 'https://github.com/hest-io'
  # features:
  #   tabs: true
  icon:
    logo: material/console
    repo: material/github

# Plugins
plugins:
- search
- mermaid2

# Extensions
markdown_extensions:
- markdown_include.include:
    base_path: docs/includes
- markdown.extensions.admonition
- markdown.extensions.codehilite:
    guess_lang: false
    linenums: true
- markdown.extensions.def_list
- markdown.extensions.footnotes
- markdown.extensions.meta
- markdown.extensions.toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- pymdownx.superfences
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format


# Addition JS and CSS
extra_css:
- https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
- theme/css/hestio-theme.css

extra_javascript:
- https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js


# Sitemap
nav:
- 'Getting Started': 'index.md'
- 'User Guide':
  - 'Setup AWS Access': 'user-guide/auth-setup.md'
- 'Contributor Guide':
  - 'Getting Involved': 'placeholder.md'
  - 'Contributing Filters': 'placeholder.md'
  - 'Contributing Commands': 'placeholder.md'
  - 'Contributing Docs': 'placeholder.md'
- 'Advanced Usage':
  - 'Overview': 'placeholder.md'  
- 'About the Project':
  - 'Release Notes': 'placeholder.md'
- 'FAQ': 'placeholder.md'